# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAP.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(967, 620)
        self.comboBox_Videos = QtGui.QComboBox(Form)
        self.comboBox_Videos.setGeometry(QtCore.QRect(10, 70, 321, 27))
        self.comboBox_Videos.setObjectName(_fromUtf8("comboBox_Videos"))
        self.comboBox_Videos.addItem(_fromUtf8(""))
        self.comboBox_Videos.addItem(_fromUtf8(""))
        self.commandLinkButton_Run = QtGui.QCommandLinkButton(Form)
        self.commandLinkButton_Run.setGeometry(QtCore.QRect(290, 570, 61, 41))
        self.commandLinkButton_Run.setObjectName(_fromUtf8("commandLinkButton_Run"))
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(380, 10, 581, 601))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.PyLab = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.PyLab.setObjectName(_fromUtf8("PyLab"))
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 101, 135))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_QP = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_QP.setObjectName(_fromUtf8("verticalLayout_QP"))
        self.radioButton_QP22 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_QP22.setObjectName(_fromUtf8("radioButton_QP22"))
        self.verticalLayout_QP.addWidget(self.radioButton_QP22)
        self.radioButton_QP27 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_QP27.setObjectName(_fromUtf8("radioButton_QP27"))
        self.verticalLayout_QP.addWidget(self.radioButton_QP27)
        self.radioButton_QP32 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_QP32.setObjectName(_fromUtf8("radioButton_QP32"))
        self.verticalLayout_QP.addWidget(self.radioButton_QP32)
        self.radioButton_QP47 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_QP47.setObjectName(_fromUtf8("radioButton_QP47"))
        self.verticalLayout_QP.addWidget(self.radioButton_QP47)
        self.spinBox_Frames = QtGui.QSpinBox(Form)
        self.spinBox_Frames.setGeometry(QtCore.QRect(10, 310, 105, 27))
        self.spinBox_Frames.setObjectName(_fromUtf8("spinBox_Frames"))
        self.comboBox_Profiles = QtGui.QComboBox(Form)
        self.comboBox_Profiles.setGeometry(QtCore.QRect(10, 30, 321, 27))
        self.comboBox_Profiles.setObjectName(_fromUtf8("comboBox_Profiles"))
        self.comboBox_Profiles.addItem(_fromUtf8(""))
        self.comboBox_Profiles.addItem(_fromUtf8(""))
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 140, 101, 135))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_SR = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_SR.setObjectName(_fromUtf8("verticalLayout_SR"))
        self.radioButton_SR08 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_SR08.setObjectName(_fromUtf8("radioButton_SR08"))
        self.verticalLayout_SR.addWidget(self.radioButton_SR08)
        self.radioButton_SR16 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_SR16.setObjectName(_fromUtf8("radioButton_SR16"))
        self.verticalLayout_SR.addWidget(self.radioButton_SR16)
        self.radioButton_SR32 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_SR32.setObjectName(_fromUtf8("radioButton_SR32"))
        self.verticalLayout_SR.addWidget(self.radioButton_SR32)
        self.radioButton_SR64 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_SR64.setObjectName(_fromUtf8("radioButton_SR64"))
        self.verticalLayout_SR.addWidget(self.radioButton_SR64)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 360, 101, 135))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_L1 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_L1.setObjectName(_fromUtf8("verticalLayout_L1"))
        self.radioButton_L108 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_L108.setObjectName(_fromUtf8("radioButton_L108"))
        self.verticalLayout_L1.addWidget(self.radioButton_L108)
        self.radioButton_L116 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_L116.setObjectName(_fromUtf8("radioButton_L116"))
        self.verticalLayout_L1.addWidget(self.radioButton_L116)
        self.radioButton_L132 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_L132.setObjectName(_fromUtf8("radioButton_L132"))
        self.verticalLayout_L1.addWidget(self.radioButton_L132)
        self.verticalLayoutWidget_4 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(170, 360, 101, 135))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_LL = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_LL.setObjectName(_fromUtf8("verticalLayout_LL"))
        self.radioButton_LL04 = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_LL04.setObjectName(_fromUtf8("radioButton_LL04"))
        self.verticalLayout_LL.addWidget(self.radioButton_LL04)
        self.radioButton_LL08 = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_LL08.setObjectName(_fromUtf8("radioButton_LL08"))
        self.verticalLayout_LL.addWidget(self.radioButton_LL08)
        self.radioButton_LL16 = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_LL16.setObjectName(_fromUtf8("radioButton_LL16"))
        self.verticalLayout_LL.addWidget(self.radioButton_LL16)
        self.comboBox_Word = QtGui.QComboBox(Form)
        self.comboBox_Word.setGeometry(QtCore.QRect(10, 560, 80, 27))
        self.comboBox_Word.setObjectName(_fromUtf8("comboBox_Word"))
        self.comboBox_Word.addItem(_fromUtf8(""))
        self.comboBox_Word.addItem(_fromUtf8(""))
        self.comboBox_AssL1 = QtGui.QComboBox(Form)
        self.comboBox_AssL1.setGeometry(QtCore.QRect(10, 510, 80, 27))
        self.comboBox_AssL1.setObjectName(_fromUtf8("comboBox_AssL1"))
        self.comboBox_AssL1.addItem(_fromUtf8(""))
        self.comboBox_AssL1.addItem(_fromUtf8(""))
        self.comboBox_AssL1.addItem(_fromUtf8(""))
        self.comboBox_AssLL = QtGui.QComboBox(Form)
        self.comboBox_AssLL.setGeometry(QtCore.QRect(170, 510, 80, 27))
        self.comboBox_AssLL.setObjectName(_fromUtf8("comboBox_AssLL"))
        self.comboBox_AssLL.addItem(_fromUtf8(""))
        self.comboBox_AssLL.addItem(_fromUtf8(""))
        self.comboBox_AssLL.addItem(_fromUtf8(""))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.comboBox_Videos.setItemText(0, _translate("Form", "BasketballPass", None))
        self.comboBox_Videos.setItemText(1, _translate("Form", "BQMall", None))
        self.commandLinkButton_Run.setText(_translate("Form", "Run", None))
        self.radioButton_QP22.setText(_translate("Form", "22", None))
        self.radioButton_QP27.setText(_translate("Form", "27", None))
        self.radioButton_QP32.setText(_translate("Form", "32", None))
        self.radioButton_QP47.setText(_translate("Form", "37", None))
        self.comboBox_Profiles.setItemText(0, _translate("Form", "Random Access", None))
        self.comboBox_Profiles.setItemText(1, _translate("Form", "Low Delay", None))
        self.radioButton_SR08.setText(_translate("Form", "8", None))
        self.radioButton_SR16.setText(_translate("Form", "16", None))
        self.radioButton_SR32.setText(_translate("Form", "32", None))
        self.radioButton_SR64.setText(_translate("Form", "64", None))
        self.radioButton_L108.setText(_translate("Form", "8", None))
        self.radioButton_L116.setText(_translate("Form", "16", None))
        self.radioButton_L132.setText(_translate("Form", "32", None))
        self.radioButton_LL04.setText(_translate("Form", "4", None))
        self.radioButton_LL08.setText(_translate("Form", "8", None))
        self.radioButton_LL16.setText(_translate("Form", "16", None))
        self.comboBox_Word.setItemText(0, _translate("Form", "32", None))
        self.comboBox_Word.setItemText(1, _translate("Form", "64", None))
        self.comboBox_AssL1.setItemText(0, _translate("Form", "1", None))
        self.comboBox_AssL1.setItemText(1, _translate("Form", "2", None))
        self.comboBox_AssL1.setItemText(2, _translate("Form", "4", None))
        self.comboBox_AssLL.setItemText(0, _translate("Form", "1", None))
        self.comboBox_AssLL.setItemText(1, _translate("Form", "2", None))
        self.comboBox_AssLL.setItemText(2, _translate("Form", "4", None))

